# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
workflows:
  version: 2
  init_and_test:
    jobs:
      - validate
      - plan:
        requires: validate



jobs:
  validate:
    #branches:
      #only:
      #  - master
    docker:
        - image: hashicorp/terraform
    steps:
        - checkout
        - run: terraform init
        - run: terraform validate
  plan:
    docker:
        - image: hashicorp/terraform
    steps:
        - checkout
        - run: terraform init
        - run: terraform plan --var-file="test.tfvars"




  #      - run: terraform validate
  #      - run: terraform plan -var-file="sdx.tfvars"
