# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
workflows:
  version: 2
  init_and_test:
    jobs:
      - validate
      - plan:
          requires:
            - validate
          context: wefit_aws

      - deploy:
          filter:
            branch:
              only:
                - master
          requires:
            - validate
            - plan
          context: wefit_aws

      - destroy:
          filter:
            branch:
              only:
                - master
          requires:
            - deploy
          context: wefit_aws
          filters:
            branches:
              only: master




jobs:
  validate:
    docker:
        - image: hashicorp/terraform
    steps:
        - checkout
        - run: terraform init -backend-config=test.tfvars
        - run: terraform validate
  plan:
    branches:
    docker:
        - image: hashicorp/terraform
    steps:
        - checkout
        - run: terraform init -backend-config=test.tfvars
        - run: terraform plan --var-file="test.tfvars"


  deploy:
    docker:
        - image: hashicorp/terraform
    steps:
        - checkout
        - run: terraform init -backend-config=test.tfvars
        - run: terraform apply -auto-approve --var-file="test.tfvars"


  destroy:
    docker:
        - image: hashicorp/terraform
    steps:
        - checkout
        - run: terraform init -backend-config=test.tfvars
        - run: terraform destroy -auto-approve --var-file="test.tfvars"
