# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
jobs:
  build:
    #branches:
      #only:
      #  - master
    docker:
        - image: hashicorp/terraform
    steps:
        - checkout
        - run: terraform init
  test:
    docker:
        - image: hashicorp/terraform
    steps:
        - checkout
        - run: terraform validate
workflows:
  version: 2
  init_and_test:
    jobs:
      - build
      - test


  #      - run: terraform validate
  #      - run: terraform plan -var-file="sdx.tfvars"
