# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
workflows:
  version: 2
  init_and_test:
    jobs:
      - validate
      - plan:
          requires:
            - validate
          context: wefit_aws



jobs:
  validate:
    #branches:
      #only:
      #  - master
    docker:
        - image: hashicorp/terraform
    steps:
        - checkout
        - run: terraform init -backend-config=test.tfvars
        - run: terraform validate
  plan:
    docker:
        - image: hashicorp/terraform
    steps:
        - checkout
        - run: terraform init -backend-config=test.tfvars
        - run: terraform plan --var-file="test.tfvars"
