name: Terraform
on:
  push:
    branches:
    - master
  pull_request:
env:
  TF_ACTIONS_VERSION: 0.12.13 
jobs:
  check-format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 'Terraform Format'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate-examples:
    name: Validate code 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 'Terraform Init - stack'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Terraform Validate - stack'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}